version: '2'
services:
  rethinkdb_service:
    image: rethinkdb:latest

  mongodb_service:
    image: mongo:latest

  consul_service:
    image: gliderlabs/consul-server:latest
    hostname: "consul"
    ports:
      - "8500:8500"
    command: "-server -bootstrap"

  fabio_service:
    image: magiconair/fabio:latest
    hostname: fabio
    ports:
      - "80:9999"
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
